### ISSUE TITLE
Roadmap 👾

### ISSUE THREAD

**Issue by SabrinaBarros** [SabrinaBarros/ditto-boilerplate#1]
# v0.2.0

**New features**

- [ ] Navigation menu
- [ ] Create Static Pages

**Improvements**

- [x] Change to Stylus c2d742ee88b7257b71d22b82b30a3392a4bd6782
- [x] Add SMACSS c2d742ee88b7257b71d22b82b30a3392a4bd6782
- [ ] Refactor HTML with Pug
- [ ] Add Task Runner

# v0.3.0

- [ ] Single Page App

# v0.4.0

- [ ] Dinamic Content from REST API

# Backlog

- [ ] Add StyleLint
- [ ] Add Favicon
- [ ] Add Twitter Card
- [ ] Add Open Graph
