### ISSUE TITLE
Roadmap 👾

### ISSUE THREAD

**Issue by SabrinaBarros** [SabrinaBarros/ditto-boilerplate#2]
# v0.2.0

**New features**

- [ ] #3
- [ ] #4

**Improvements**

- [x] Change to Stylus c2d742ee88b7257b71d22b82b30a3392a4bd6782
- [x] Add SMACSS c2d742ee88b7257b71d22b82b30a3392a4bd6782
- [ ] #5
- [ ] #6

# v0.3.0

- [ ] #10

# v0.4.0

- [ ] #11

# Backlog

- [ ] Add StyleLint
- [ ] Add Favicon
- [ ] Add Twitter Card
- [ ] Add Open Graph
